export const registrants = [
'Abigail Denney',
'Aditya Vijaykumar',
'Affan Khadir',
'Alejandro (Alex) Ortega',
'Alex Laroche',
'Alexander (Alex) Valencia',
'Ana Pago',
'Anannya Gogoi',
'Austin Brown',
'Aviad Levis',
'Ayush Pandhi',
'Biprateep Dey',
'Bushra Haque',
'Dayi David Li',
'Devon Lin',
'Diego Montalvo',
'Diksha Chaudhury',
'Doğa  Tolgay',
'Duo Xu',
'Ethan Kwan',
'Falisha Shoun',
'Grace Connolly',
'Gwendolyn (Gwen) Eadie',
'Hannah Semple',
'Huanlin Mao',
'Inessa De Angelis',
'Irmak Aytekin',
'Isaac Rosenberg',
'Ismaila Ba',
'Ivan Tockovski',
'Jeffrey Rosenthal',
'Jennifer Chan',
'Justin Shaw',
'Kal Romain',
'Kevin McKinnon',
'Laurie Rousseau-Nepton',
'Leo Watson',
'Liam Welsh',
'Mairead Heiger',
'Mandy Yao',
'Marjan Rajabi',
'Matteo Moretti',
'Meredith Franklin',
'Nasser Mohammed',
'Nathan Sandford',
'Paul Scholz',
'Pauline Barmby',
'Pavan Vynatheya',
'Phil Van-Lane',
'Ping Lin',
'Radu Craiu',
'Rahul Krishnan',
'Renée Hlozek',
'Rodrigo Herrera',
'Rohan Alexander',
'Sabrina Sixta',
'Sam Berek',
'Sebastian Calcetero',
'Thibault Randrianarisoa',
'Tim Zheng',
'Vedant Choudhary',
'Vijay Mamtani',
'Wai Yu (Amanda) Ng',
'Yoyo Lin',
'Yuhan Pan'
]